# -*- coding: utf-8 -*-
"""Projekt1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n6Nh_h0jNwnigHhGl-YBEzLsPOBzLRi-
"""

from shapely.geometry import Polygon
#p = Polygon([[0, 0], [1, 0], [1, 1], [0, 1],])

import geojson
with open('map.geoJSON') as f:
    data = geojson.load(f)

#creating list of points
list1 =[]
for feature in data['features']:
    print(feature['geometry']['type'])
    print(feature['geometry']['coordinates'])
    list1.append(feature['geometry']['coordinates'])
print('\r')
print(list1)
print(list1[0])
print('\r')

#creating max and min points for bounding box
def max_min(point):
  xmax = point[0] + 0.01
  xmin = point[0] - 0.01
  ymax = point[1] + 0.015
  ymin = point[1] - 0.015
  return [xmin, ymin], [xmin, ymax], [xmax, ymax], [xmax, ymin]
max_min(list1[0])

#creating bounding box
def polygon(list_of_points):
  p = Polygon(list_of_points)
  return p

polygon(max_min(list1[0]))

from google.colab import data_table
data_table.enable_dataframe_formatter()
from vega_datasets import data

cars = data.cars()
cars

import folium
import pandas as pd

#creating map
def map(zoom,point):
  my_map = folium.Map(
      location=point,
      zoom_start=zoom
  )
  return my_map
map(2,[13.133932434766733, 16.103938729508073])

from pandas._libs import index
import geopandas as gpd
file = 'map.geoJSON'
tab = gpd.read_file(file)
tab.head(9)

list1 =[]
for feature in data['features']:
    list1.append(feature['geometry']['coordinates'])

x0 = (polygon(max_min(list1[0])))
x1 = (polygon(max_min(list1[1])))
x2 = (polygon(max_min(list1[2])))
x3 = (polygon(max_min(list1[3])))
x4 = (polygon(max_min(list1[4])))
x5 = (polygon(max_min(list1[5])))
x6 = (polygon(max_min(list1[6])))
x7 = (polygon(max_min(list1[7])))
x8 = (polygon(max_min(list1[8])))

list2 = []
for i in range(len(list1)):
  x = max_min(list1[i])
  #print(x)
  list2.append((x))

xmin_ymin_list = []
for i in range(len(list2)):
  xmin_ymin_list.append(list2[i][0])
#print(xmin_ymin_list)

xmin_ymax_list = []
for i in range(len(list2)):
  xmin_ymax_list.append(list2[i][1])
#print(xmin_ymax_list)

xmax_ymax_list = []
for i in range(len(list2)):
  xmax_ymax_list.append(list2[i][2])
#print(xmax_ymax_list)

xmax_ymin_list = []
for i in range(len(list2)):
  xmax_ymin_list.append(list2[i][3])
#print(xmax_ymin_list)

tab = tab.assign(point1=xmin_ymin_list)
tab = tab.assign(point2=xmin_ymax_list)
tab = tab.assign(point3=xmax_ymax_list)
tab = tab.assign(point4=xmax_ymin_list)

tab = tab.assign(polygon=x0)

tab.at[1, 'polygon']=x1
tab.at[2, 'polygon']=x2
tab.at[3, 'polygon']=x3
tab.at[4, 'polygon']=x4
tab.at[5, 'polygon']=x5
tab.at[6, 'polygon']=x6
tab.at[7, 'polygon']=x7
tab.at[8, 'polygon']=x8

tab.head(9)

import folium
import geojson
with open('map.geoJSON') as f:
    data = geojson.load(f)
list1 =[]
for feature in data['features']:
    list1.append(feature['geometry']['coordinates'])


def map(zoom,point):
  my_map = folium.Map(
      location=point,
      zoom_start=zoom
  )
  return my_map    

my_map = map(2,[13.133932434766733, 16.103938729508073])   
#adding coordinate points to the map
def points(zoom):
  for i in range(9):
    print(list1[i])
    x = float(list1[i][0])/zoom
    y = float(list1[i][1])/zoom
    print([x,y])
    print('\r')
    folium.Marker(location=[x,y]).add_to(my_map)
  return my_map

points(2)

#my_map = (map(8,[33.178667000000004, 54.561241])).fit_bounds(tab['point1'][0], tab['point3'][0])
new_map = map(7,[33.178667000000004, 54.561241])
folium.FitBounds([tab['point1'][0],tab['point3'][0]]).add_to(new_map)
new_map

"""# Nowa sekcja"""

import urllib.request

opener = urllib.request.FancyURLopener({})
url = "https://app.spectator.earth"
f = opener.open(url)
content = f.read()

import urllib.request
fid=urllib.request.urlopen('https://app.spectator.earth')
webpage=fid.read().decode('utf-8')
print(webpage)
#
content="https://api.spectator.earth/observation/056fbcbc-d9be-4815-be65-2e2a731e0e3a/imagery/22876929/files/preview.jpg/?as_attachment=false"
print(content)

